apiVersion: v1
kind: Service
metadata:
  name: gke-monorepo-frontend
spec:
  selector:
    app: gke-monorepo-frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer