apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-bazel
spec:
  selector:
    matchLabels:
      app: skaffold-bazel
  replicas: 1
  template:
    metadata:
      labels:
        app: skaffold-bazel
    spec:
      containers:
      - name: skaffold-bazel
        image: gcr.io/agmsb-k8s/skaffold-bazel
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080